### ISSUE TITLE
Neo support

### ISSUE THREAD

**Issue by awcross** [verbb/field-manager#37]
Cloning seems to work fine but nothing is exported when using [Neo](https://github.com/benjamminf/craft-neo).

**Comment by engram-design** [comment]
Adding this as a feature question - Field Manages doesn't currently support Neo fields.

**Comment by jrmd** [comment]
@engram-design any news on if this will be implemented

**Comment by maxwellhibbert** [comment]
This is a big want for me too

**Comment by SimonEast** [comment]
Yeah I just discovered this issue today too. Maybe the readme should be updated in the meantime until support is added.

**Comment by 23d1** [comment]
Any ETA (or plans at all) to implement Neo fields for import/export? Would be a total life saver.

**Comment by svenjungnickel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adding support for Neo field type](https://trello.com/c/Qn586H2t/6-adding-support-for-neo-field-type)

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/field-manager/releases/tag/2.1.0)
