### ISSUE TITLE
Export to an input field instead of a downloadable file.

### ISSUE THREAD

**Issue by bhuvidya** [verbb/field-manager#40]
A lot of times I find myself copying a block of fields from one site to another. As importing is done by pasting JSON into an input field, it would be a much slicker workflow to be able to just do an export on the first site into a text field that can be copied, and then I all would have to do is paste the JSON into the import field on the target site.

If I get time I might do a PR for this.

**Comment by engram-design** [comment]
So instead of an export file being downloaded, just output the JSON into a text area for copy/paste? Seems reasonable!

**Comment by bhuvidya** [comment]
Yeh mate, that's the gist of it. I know with Craft 3 on the horizon it might not be so appealing to maintain these plugins but all I can say is Super Table and Field Manager go on every Craft site I do. Thanks for your efforts, they have saved me a lot of time and made Craft even better.

**Comment by engram-design** [comment]
@bhuvidya Great to hear you use them so often, and they're still actively maintained! In the thick of updating for Craft 3, so any features requests or improvements are always welcome.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/field-manager/releases/tag/2.1.0)
