### ISSUE TITLE
Controlpanel icon

### ISSUE THREAD

**Issue by mdominguez** [verbb/field-manager#43]
Not really an issue but still.. :)

![field_manager_-_crunch_analytics](https://user-images.githubusercontent.com/1449125/31848858-252d86f2-b63a-11e7-9975-3da8bb1aadda.png)

**Comment by engram-design** [comment]
Saw that just after the release! Fixed in the latest master at least...

**Comment by mdominguez** [comment]
Woops saw it :) great plugin, thanks!
