### ISSUE TITLE
changelog.json errors

### ISSUE THREAD

**Issue by pixelmachine** [verbb/field-manager#46]
Hey, couple of small things in changelog.json.

The download URL is missing a letter: field-manage**R**:
`"downloadUrl": "https://github.com/verbb/field-manage/archive/1.5.5.zip",`

The version number in FieldManagerPlugin.php doesn't match the current version.

**Comment by groe** [comment]
Yup, the download button in craft 404s: https://github.com/verbb/field-manage/archive/1.5.5.zip

**Comment by engram-design** [comment]
Sorry about that guys, typo! Should be fixed.
